### ISSUE TITLE
Implement popups based on errors

### ISSUE THREAD

**Issue by shivam1317** [shivam1317/awesome-goal-tracker#6]
Whenever some error occurs during login,signup or logout then there must be different popups for different errors.

For example:

- If user email is already used 
- If user doesn't exist
- If password is not strong
- If email is invalid

I have added some example error messages from firebase in [signup,.js](https://github.com/shivam1317/awesome-goal-tracker/blob/main/pages/signup.js)

**Comment by michaelessiet** [comment]
Try adding alert(error.message) to the 

catch (error) {

      // Show different popups on different errors:
      // 1. Firebase: Error (auth/email-already-in-use).
      // 2. Firebase: Password should be at least 6 characters (auth/weak-password).
      console.log(error.message);
      👉 alert(error.message);  //Like this
      setUserDetails({
        username: "",
        email: "",
        password: "",
      });
    }


it should bring a popup on the browser window of the exact error message in the popup.

**Comment by shivam1317** [comment]
Hello there,

I am going to do this with `react-toastify` because alert looks very simple.
Thanks.
